### ISSUE TITLE
Version 1.2 and up crashing on startup

### ISSUE THREAD

**Issue by FluidExtractor** [63OR63/zonepaq#3]
Version 1.2 and up of zonepaq crash on launch with the following error: 
![12_12_24_16 20_7](https://github.com/user-attachments/assets/80ccd751-af58-413d-8435-7507cb553fa2)

This happens when latest zonepaq tries using the settings.ini generated by a version that didn't have the functionality to unpack encrypted vanilla files. Deleting the old config, and letting it generate a new one solves this. Seems that the new versions aren't trying to append the AES key to the old config, but instead they see the existing config and complain that the AES key is missing.

**Comment by 63OR63** [comment]
The issue occurs because I introduced a new configuration variable for unpacking vanilla files. The current implementation of the config loader is flawed, as it requires either all or none of the settings to be present. I will address this behavior in a future release.

For now, you can resolve the error by deleting the `settings.ini` file located in the same folder as the executable. This will reset the settings to their default values, including `AES_KEY`.

**Comment by 63OR63** [comment]
Thank you for pointing that out. You’ve correctly identified the issue and its potential solution. I will address this behavior in a future release.

**Comment by 63OR63** [comment]
Fixed in v1.3.1
